### ISSUE TITLE
Error running in CLI mode

### ISSUE THREAD

**Issue by Mecanik** [Mecanik/ZF3Turbo#3]
I was wondering why my cron was not working, a fix is needed to ignore CLI mode:

```
[21-Jan-2020 20:03:42 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined method Zend\Console\Response::getBody() in /home/*****/public_html/vendor/mecanik/zf3turbo/src/Listener/ZF3TurboListener.php:82
Stack trace:
#0 /home/*****/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Mecanik\ZF3Turbo\Listener\ZF3TurboListener->onFinish(Object(Zend\Mvc\MvcEvent))
#1 /home/*****/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#2 /home/*****/public_html/vendor/zendframework/zend-mvc/src/Application.php(371): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#3 /home/*****/public_html/vendor/zendframework/zend-mvc/src/Application.php(326): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#4 /home/*****/public_html/public/index.php(45): Zend\Mvc\Application->run()
#5 {main}
  thrown in /home/*****/public_html/vendor/mecanik/zf3turbo/src/Listener/ZF3TurboListener.php on line 82
```

**Comment by Mecanik** [comment]
Fixed in #aafdc30
